# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name: "8퍼센트 프로덕트 블로그"

authors:
  leclipse:
    name: leclipse
    display_name: Lee Ho Sung
  seba:
    name: seba
    display_name: Seba
  ianstream:
    name: ianstream
    display_name: Kim Yeon Tae
  boo:
    name: boo
    display_name: Bu Hye Eun
  leehyunjoo:
    name: leehyunjoo
    display_name: Lee hyun joo
  seongkwonha:
    name: seongkwonha
    display_name: Ha Seong Kwon
  donghyeon:
    name: donghyeon
    display_name: Dong Hyeon Lim
  munsu:
    name: munsu
    display_name: Mun Su Park
  anohk:
    name: anohk
    display_name: An Young Noh
  bbungsang:
    name: bbungsang
    display_name: Kim Hee Jin
  namongk:
    name: namongk
    display_name: Kim Nam Hong
  jiyoon:
    name: jiyoon
    display_name: Ha Ji Yoon
  younggwan:
    name: younggwan
    display_name: Kim Young Gwan
  hyojin:
    name: hyojin
    display_name: Lee Hyo Jin
  sunyoung:
    name: sunyoung
    display_name: Yim Sun Young
  boram:
    name: boram
    display_name: Han Bo Ram
  mansu:
    name: mansu
    display_name: Shin Man Su
  bakyeono:
    name: bakyeono
    display_name: 박연오
  selee:
    name: selee
    display_name: Chae Se Lee
  minjung:
    name: minjung
    display_name: Minjung Kim
  seunghee:
    name: seunghee
    display_name: Seunghee Jo

#  facebook:         your-id
#  youtubeUser:      your-id
#  youtubeChannel:   your-id
#  twitter:          your-id
#  github:           your-id
#  stackoverflow:    your-id
#  quora:            your-id
#  linkedin:         your-id
#  pinterest:        your-id
#  googlePlus:       your-id
#  instagram:        your-id
#  reddit:           your-id
#  medium:           your-id
#  tumblr:           your-id
#  email:            your-id@your-email.com

copyright:
  start_year: 2017
  end_year: 2021
  name: 8PERCENT

# Google-analytics
#google-analytics:
#  id:               ""

# Disqus
#disqus:
#  id:               "kiko-plus"

# URL
url: "https://8percent.github.io" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl: "" # the subpath of your site, e.g. /blog

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Seoul
permalink: /:year-:month-:day/:title/

# Pagination
paginate: 5
paginate_path: /page:num/

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Navigation
nav:
  - name: "소개"
    url: "/about"
  #  - name:           "블로그"
  #    url:            "/"
  - name: "8퍼센트 브런치"
    url: "https://brunch.co.kr/magazine/8percent"
  #  - name:           "Github"
  #    url:            "https://github.com/8percent/8percent.github.io"
  - name: "채용정보"
    url: "/recruit"

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Scopes
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude: [vendor]
